// Mock data for files
export const mockFiles = [
  {
    id: "1",
    title: "Prova P1 de Cálculo I - 2023",
    description: "Prova aplicada pelo Prof. Silva no primeiro semestre de 2023.",
    type: "prova",
    course: "Cálculo I",
    courseCode: "MAT0101",
    professor: "Prof. Silva",
    semester: "2023/1",
    uploadDate: "2023-07-15",
    uploader: "Maria Santos",
    tags: ["com-gabarito", "dificil"],
    likes: 45,
    comments: 12,
  },
  {
    id: "2",
    title: "Lista de Exercícios - Física II",
    description: "Lista completa com todos os exercícios do semestre.",
    type: "lista",
    course: "Física II",
    courseCode: "FIS0202",
    professor: "Prof. Oliveira",
    semester: "2023/1",
    uploadDate: "2023-06-20",
    uploader: "João Pereira",
    tags: ["com-gabarito", "pratico"],
    likes: 32,
    comments: 8,
  },
  {
    id: "3",
    title: "Resumo de Bioquímica - Metabolismo",
    description: "Resumo completo sobre vias metabólicas.",
    type: "resumo",
    course: "Bioquímica",
    courseCode: "BIO0305",
    professor: "Profa. Santos",
    semester: "2022/2",
    uploadDate: "2023-01-10",
    uploader: "Ana Costa",
    tags: ["conceitual", "completo"],
    likes: 67,
    comments: 15,
  },
  {
    id: "4",
    title: "Prova P2 de Algoritmos - 2022",
    description: "Segunda prova da disciplina de Algoritmos e Estruturas de Dados.",
    type: "prova",
    course: "Algoritmos",
    courseCode: "MAC0121",
    professor: "Prof. Ferreira",
    semester: "2022/2",
    uploadDate: "2023-01-05",
    uploader: null,
    tags: ["dificil", "pratico"],
    likes: 28,
    comments: 6,
  },
  {
    id: "5",
    title: "Lista de Exercícios - Química Orgânica",
    description: "Lista com exercícios sobre reações orgânicas.",
    type: "lista",
    course: "Química Orgânica",
    courseCode: "QUI0203",
    professor: "Profa. Lima",
    semester: "2023/1",
    uploadDate: "2023-05-12",
    uploader: "Carlos Mendes",
    tags: ["com-gabarito"],
    likes: 19,
    comments: 4,
  },
  {
    id: "6",
    title: "Resumo de Direito Constitucional",
    description: "Resumo completo sobre princípios fundamentais.",
    type: "resumo",
    course: "Direito Constitucional",
    courseCode: "DIR0101",
    professor: "Prof. Almeida",
    semester: "2022/1",
    uploadDate: "2022-08-30",
    uploader: "Juliana Rocha",
    tags: ["conceitual", "completo"],
    likes: 53,
    comments: 9,
  },
]

// Mock data for comments
export const mockComments = [
  {
    id: "c1",
    user: {
      name: "Pedro Alves",
      avatar: "/placeholder.svg",
    },
    content: "Essa prova foi realmente difícil! Alguém conseguiu resolver a questão 3?",
    date: "2023-07-20",
    likes: 8,
  },
  {
    id: "c2",
    user: {
      name: "Mariana Costa",
      avatar: "/placeholder.svg",
    },
    content: "Obrigada por compartilhar! O gabarito ajudou muito nos meus estudos para a P2.",
    date: "2023-08-05",
    likes: 12,
  },
  {
    id: "c3",
    user: {
      name: "Lucas Ferreira",
      avatar: "/placeholder.svg",
    },
    content: "Alguém tem o material complementar que o professor recomendou para essa prova?",
    date: "2023-08-12",
    likes: 3,
  },
]
